# Generated by Django 4.2.6 on 2023-11-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
