# Generated by Django 4.2.5 on 2023-09-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_passageiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='passageiro',
            new_name='passageiros',
        ),
    ]
