# Generated by Django 4.2.6 on 2023-11-12 15:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicaçao', models.DateTimeField(default=datetime.datetime.now)),
                ('data_saida', models.DateTimeField(default=datetime.datetime.now)),
                ('origem', models.TextField(default='FAT', max_length=50)),
                ('destino', models.TextField(default='Centro', max_length=50)),
                ('preço', models.IntegerField(default=4.0)),
                ('veiculo', models.TextField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto')], default='Veiculo.CARRO', max_length=10)),
                ('modalidade', models.CharField(choices=[('CARONA', 'CARONA'), ('UBER', 'Uber')], default='Modalidade.CARONA', max_length=12)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('passageiros', models.ManyToManyField(blank=True, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
