# Generated by Django 4.2.6 on 2023-10-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnh',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
