# Generated by Django 4.2.4 on 2023-11-08 20:31

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rides.api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('placa_carro', models.CharField(blank=True, max_length=8, null=True)),
                ('cnh', models.CharField(blank=True, max_length=11, null=True, validators=[rides.api.validators.cnh_valido])),
                ('diretorio', models.ImageField(upload_to=accounts.models.upload_path)),
                ('senha', models.CharField(default='*********', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('diretorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foto_perfil', to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
