# Generated by Django 4.2.4 on 2023-11-08 20:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='diretorio',
            field=models.ImageField(upload_to=accounts.models.upload_path),
        ),
    ]
