# Generated by Django 4.2.5 on 2023-10-04 21:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diretorio',
            field=models.ImageField(upload_to=accounts.models.upload_path),
        ),
    ]
