# Generated by Django 4.2.4 on 2023-11-08 19:27

from django.db import migrations, models
import rides.api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_ativo_alter_profile_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cnh',
            field=models.CharField(blank=True, max_length=11, validators=[rides.api.validators.cnh_valido]),
        ),
    ]
