# Generated by Django 4.2.4 on 2023-10-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_diretorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
