# Generated by Django 4.2.7 on 2023-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_diretorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cnh',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
