# Generated by Django 4.2.5 on 2023-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_remove_ride_passageiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='info',
        ),
        migrations.AddField(
            model_name='ride',
            name='destino',
            field=models.TextField(default='Centro', max_length=50),
        ),
        migrations.AddField(
            model_name='ride',
            name='origem',
            field=models.TextField(default='FAT', max_length=50),
        ),
        migrations.AddField(
            model_name='ride',
            name='preço',
            field=models.IntegerField(default=4.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='veiculo',
            field=models.TextField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto')], default='Veiculo.CARRO', max_length=10),
        ),
    ]
