# Generated by Django 4.2.5 on 2023-09-25 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0003_remove_ride_info_ride_destino_ride_origem_ride_preço_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passageiro',
            field=models.ManyToManyField(blank=True, related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
