# Generated by Django 4.2.4 on 2023-11-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_diretorio'),
        ('rides', '0006_alter_ride_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passageiros',
            field=models.ManyToManyField(blank=True, related_name='passenger', to='accounts.profile'),
        ),
    ]
