# Generated by Django 4.2.4 on 2023-11-14 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rides', '0006_alter_ride_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passageiros',
            field=models.ManyToManyField(blank=True, related_name='passenger', to='accounts.user'),
        ),
    ]
