# Generated by Django 4.2.4 on 2023-11-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_diretorio'),
        ('rides', '0007_alter_ride_passageiros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='accounts.profile'),
        ),
    ]
