# Generated by Django 4.2.6 on 2023-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_remove_ride_data_saida_ride_hora_saida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
